#!/usr/bin/env python3
"""Regenerate site/data.js from the repo's own evidence.

Live sources: `gh pr list` (PR pipeline), the newest .ratchet-proof/<ts>/ run
(red team, proof checklist), and the test suite. The blocks that change rarely
(search run, receipts, gauntlet stages, cheat rules) are constants below —
update them from the proof logs when a new run changes them.
"""
from __future__ import annotations

import json
import re
import subprocess
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "site" / "data.js"

GAUNTLET = ["build", "cheat check", "fail-to-pass", "pass-to-pass", "types", "lint", "diff hygiene"]
CHEAT_RULES = [
    "hard_exit", "always_equal", "special_casing", "runtime_test_write",
    "protected_path", "skip_marker", "test_file_emptied", "test_deleted",
    "assertion_removed", "report_hook_tamper", "env_bypass", "canary_passed",
    "broad_except_pass", "log_spoofed",
]
# From .ratchet-proof/<run>/{search,search-tree,audit-*}.log — see those files.
SEARCH = {
    "run": "proof-search", "task": "demo-001-slugify", "provider": "worktree",
    "winner": "2874", "score": 1.0, "nodes": 3, "pruned": 1,
    "budget": "1/40 nodes · 0m01s · $0.00",
    "tree": ["● root  0.58", "├─✗ 1e0f  0.58  pruned", "└─★ 2874  1.00 ←live"],
}
RECEIPTS = [
    {"run": "proof-esc", "receipts": 4, "head": "b26a36f26e627c03", "chain": "intact", "green": 1, "progress": 3},
    {"run": "proof-esc-truncation", "receipts": 3, "head": "1a5db5930d9cf215", "chain": "intact", "green": 1, "progress": 2},
    {"run": "tamper demo", "receipts": 4, "head": "b26a36f26e627c03",
     "chain": "BROKEN (2 problems) — forged verdict detected", "green": 1, "progress": 3},
]
OBJECTIVE_GRAPH = {
    "graph": "demo-slugify-graph",
    "nodes": [
        {"name": "accents", "status": "fulfilled", "attempts": 1, "escalated": False},
        {"name": "truncation", "status": "fulfilled", "attempts": 3, "escalated": True},
    ],
}


def prs() -> list[dict]:
    out = subprocess.run(
        ["gh", "pr", "list", "--state", "all", "--limit", "100",
         "--json", "number,title,state,additions,deletions,url"],
        cwd=ROOT, capture_output=True, text=True, check=True,
    ).stdout
    return json.loads(out)


def latest_proof() -> Path:
    runs = sorted(p for p in (ROOT / ".ratchet-proof").iterdir() if p.is_dir())
    if not runs:
        raise SystemExit("no .ratchet-proof/ runs — run `make proof` first")
    return runs[-1]


def parse_redteam(proof: Path) -> tuple[list[dict], int, int, int]:
    rows: list[dict] = []
    caught = total = false_pos = 0
    for line in (proof / "redteam.log").read_text().splitlines():
        m = re.match(r"(\S+)\s+(\w+)\s+([\d.]+)\s+(\S+)\s+(\S*)", line.strip())
        if m and m.group(2) in ("cheated", "green", "progress", "regressed", "broken"):
            rows.append({
                "attack": m.group(1), "outcome": m.group(2),
                "score": float(m.group(3)), "stoppedAt": m.group(4),
                "findings": "" if m.group(5) in ("-", "") else m.group(5).replace(",", ", "),
            })
        if line.startswith("caught "):
            caught, total = (int(n) for n in re.findall(r"(\d+)/(\d+)", line)[0])
        if line.startswith("false positives"):
            false_pos = int(line.rsplit(":", 1)[1])
    return rows, caught, total, false_pos


def count_tests() -> int:
    return sum((f.read_text().count("def test")) for f in (ROOT / "tests").glob("test_*.py"))


def main() -> None:
    pr_rows = prs()
    proof = latest_proof()
    redteam, caught, total, false_pos = parse_redteam(proof)
    checks = [line[6:].strip() for line in (proof / "SUMMARY.txt").read_text().splitlines()
              if line.startswith("PASS")]

    data = {
        "generated": date.today().isoformat(),
        "repo": "https://github.com/ayaangazali/ratchet",
        "stats": {
            "redteamCaught": caught, "redteamTotal": total, "falsePositives": false_pos,
            "tests": count_tests(),
            "proofChecksPassed": len(checks), "proofChecksTotal": len(checks),
            "gauntletStages": len(GAUNTLET),
            "prsOpen": sum(1 for p in pr_rows if p["state"] == "OPEN"),
            "prsMerged": sum(1 for p in pr_rows if p["state"] == "MERGED"),
        },
        "prs": pr_rows,
        "redteam": redteam,
        "proofChecks": checks,
        "receipts": RECEIPTS,
        "search": SEARCH,
        "objectiveGraph": OBJECTIVE_GRAPH,
        "gauntlet": GAUNTLET,
        "cheatRules": CHEAT_RULES,
    }
    OUT.write_text(
        "// Generated by scripts/build_site_data.py — do not edit by hand\n"
        "window.RATCHET_DATA = "
        + json.dumps(data, indent=2, ensure_ascii=False)
        + ";\n"
    )
    print(f"wrote {OUT.relative_to(ROOT)} · proof run {proof.name} · "
          f"{len(pr_rows)} PRs · redteam {caught}/{total}, {false_pos} false positives")


if __name__ == "__main__":
    main()
