#!/usr/bin/env python3
"""Inline pixel-art assets into the dashboard page as data URIs.

The dashboard server serves exactly one file and must work with no CDN and no
static-file routes, so sprite sheets are embedded as base64 between the
__ASSETS_START__ / __ASSETS_END__ markers in ratchet/dashboard/index.html.

Assets come from Pixel Agents (github.com/pixel-agents-hq/pixel-agents, MIT).
Usage: python scripts/embed_dashboard_assets.py /path/to/pixel-agents
"""
from __future__ import annotations

import base64
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAGE = ROOT / "ratchet" / "dashboard" / "index.html"

# name -> path relative to <pixel-agents>/webview-ui/public/assets/
WANTED = {
    "char0": "characters/char_0.png",
    "char1": "characters/char_1.png",
    "char2": "characters/char_2.png",
    "char3": "characters/char_3.png",
    "char4": "characters/char_4.png",
    "char5": "characters/char_5.png",
    "desk": "furniture/DESK/DESK_FRONT.png",
    "pcOff": "furniture/PC/PC_FRONT_OFF.png",
    "pcOn1": "furniture/PC/PC_FRONT_ON_1.png",
    "pcOn2": "furniture/PC/PC_FRONT_ON_2.png",
    "pcOn3": "furniture/PC/PC_FRONT_ON_3.png",
    "plant": "furniture/PLANT/PLANT.png",
    "cactus": "furniture/CACTUS/CACTUS.png",
    "shelf": "furniture/DOUBLE_BOOKSHELF/DOUBLE_BOOKSHELF.png",
    "whiteboard": "furniture/WHITEBOARD/WHITEBOARD.png",
    "bin": "furniture/BIN/BIN.png",
    "bench": "furniture/CUSHIONED_BENCH/CUSHIONED_BENCH.png",
    "floor": "floors/floor_2.png",
    "pet": "pets/claudio/pet.png",
}

START = "// __ASSETS_START__"
END = "// __ASSETS_END__"


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    assets_root = Path(sys.argv[1]) / "webview-ui" / "public" / "assets"

    lines = [START + " (generated by scripts/embed_dashboard_assets.py — Pixel Agents, MIT)"]
    lines.append("const ASSETS = {")
    total = 0
    for name, rel in WANTED.items():
        data = (assets_root / rel).read_bytes()
        total += len(data)
        lines.append(f'  {name}: "data:image/png;base64,{base64.b64encode(data).decode()}",')
    lines.append("};")
    lines.append(END)
    block = "\n".join(lines)

    html = PAGE.read_text()
    pre, _, rest = html.partition(START)
    _, _, post = rest.partition(END)
    if not rest:
        raise SystemExit(f"markers not found in {PAGE}")
    PAGE.write_text(pre + block + post)
    print(f"embedded {len(WANTED)} assets ({total // 1024} KiB raw) into {PAGE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
