"""The session report behind `/export`.

Everything the console knows about what a session actually did, written to one
markdown file: the chat turns and what each produced, the commits they became,
the search nodes the verifier graded, and whether the receipt chain still checks
out. Pure -- it takes the session and the bus and returns text -- so it is
testable without a terminal and identical from the CLI.
"""

from __future__ import annotations

import json
import subprocess
import time
from pathlib import Path

from .bus import Bus
from .providers import redact


def _git(repo: Path, *args: str) -> str:
    try:
        r = subprocess.run(["git", *args], cwd=repo, capture_output=True, text=True, timeout=20)
        return r.stdout.strip() if r.returncode == 0 else ""
    except (OSError, subprocess.SubprocessError):
        return ""


def build(repo: Path, *, turns=(), bus_path: Path | None = None, work_seconds: float = 0.0) -> str:
    repo = Path(repo)
    now = time.strftime("%Y-%m-%d %H:%M:%S")
    out: list[str] = [
        f"# ratchet session — {repo.name}",
        "",
        f"`{repo}`  ·  {now}",
        "",
    ]

    # ---- headline ---------------------------------------------------------
    ok = [t for t in turns if t.ok]
    files = list(dict.fromkeys(f for t in turns for f in t.files))
    commits = [t.commit for t in turns if t.commit]
    out += [
        "## Summary",
        "",
        f"| turns | {len(turns)} ({len(ok)} landed, {len(turns) - len(ok)} failed or interrupted) |",
        "|---|---|",
        f"| files written | {len(files)} |",
        f"| commits | {len(commits)} |",
        f"| time spent working | {int(work_seconds)}s |",
        "",
    ]

    # ---- what each turn did ----------------------------------------------
    if turns:
        out += ["## Chat turns", "", "| # | asked | did | files | commit | took | outcome |",
                "|---|---|---|---|---|---|---|"]
        for i, t in enumerate(turns, 1):
            outcome = "ok" if t.ok else ("interrupted" if t.cancelled else f"failed: {t.error[:60]}")
            out.append(
                f"| {i} | {redact(t.prompt)[:60]} | {t.intent[:60] or '—'} | "
                f"{', '.join(t.files) or '—'} | `{t.commit or '—'}` | {t.seconds}s | {outcome} |"
            )
        out.append("")

    # ---- the commit trail -------------------------------------------------
    log = _git(repo, "log", "--oneline", "-20", "--grep=ratchet chat")
    if log:
        out += ["## Commits", "", "```", log, "```", ""]

    # ---- what the verifier graded ----------------------------------------
    if bus_path and Path(bus_path).exists():
        events = Bus(Path(bus_path)).read_all()
        added = [e for e in events if e.kind == "node.added"]
        pruned = [e for e in events if e.kind == "node.pruned"]
        graph = [e for e in events if e.kind.startswith("graph.node.")]
        if added or pruned or graph:
            out += ["## Verifier", "",
                    f"- nodes kept: **{len(added)}**, pruned: **{len(pruned)}**"]
            green = [e for e in added if e.payload.get("green")]
            if green:
                out.append(f"- green: {', '.join(str(e.payload.get('id')) for e in green)}")
            for e in pruned[:10]:
                out.append(f"  - pruned `{e.payload.get('id')}` — {e.payload.get('reason', '')[:80]}")
            for e in graph:
                out.append(f"  - graph `{e.payload.get('node')}` — {e.kind.split('.')[-1]}")
            out.append("")

    # ---- receipts ---------------------------------------------------------
    receipts = sorted((repo / ".ratchet").glob("*.receipts.jsonl")) if (repo / ".ratchet").is_dir() else []
    if receipts:
        from .receipts import ReceiptBook

        out += ["## Receipts", ""]
        for r in receipts[-3:]:
            book = ReceiptBook(r)
            good, problems = book.verify()
            out.append(f"- `{r.name}` — {len(book.all())} receipts, "
                       f"{'chain intact' if good else 'CHAIN BROKEN: ' + '; '.join(problems[:2])}")
        out.append("")

    # ---- the diff, last, because it is the longest ------------------------
    diff = _git(repo, "diff", "--stat", f"HEAD~{len(commits)}", "HEAD") if commits else ""
    if diff:
        out += ["## Net change", "", "```", diff, "```", ""]

    out += ["---", "", "Generated by `ratchet /export`. Every chat turn above is one commit; "
            "`git revert` undoes any of them."]
    return "\n".join(out)


def write(repo: Path, *, turns=(), bus_path: Path | None = None, work_seconds: float = 0.0) -> Path:
    text = build(repo, turns=turns, bus_path=bus_path, work_seconds=work_seconds)
    d = Path(repo) / ".ratchet"
    d.mkdir(parents=True, exist_ok=True)
    path = d / f"session-{time.strftime('%Y%m%d-%H%M%S')}.md"
    path.write_text(text)
    return path


def to_json(repo: Path, *, turns=(), work_seconds: float = 0.0) -> str:
    """The same facts, machine-readable, for anyone scripting on top."""
    return json.dumps(
        {
            "repo": str(repo),
            "generated_at": time.time(),
            "work_seconds": round(work_seconds, 1),
            "turns": [
                {"prompt": redact(t.prompt), "intent": t.intent, "files": t.files,
                 "commit": t.commit, "seconds": t.seconds, "ok": t.ok, "error": redact(t.error)}
                for t in turns
            ],
        },
        indent=2,
    )
