"""Generated by `scripts/make_mascot.py`. Do not hand-edit -- edit the geometry there.

A sprite is a grid of palette characters, one per pixel, with "." for transparent.
`ratchet.tui.mascot` turns it into half-block text: two stacked pixels per terminal
cell, which is what makes the pixels come out square rather than stretched.
"""

from __future__ import annotations

from typing import NamedTuple


class Sprite(NamedTuple):
    width: int
    height: int
    rows: tuple[str, ...]


#: Grid character -> hex colour.
PALETTE: dict[str, str] = {
    "L": "#7fb8e6",
    "M": "#4d8fc9",
    "D": "#2d5f94",
    "S": "#16324f",
    "P": "#d5e8f8",
    "E": "#3a6ea8",
    "K": "#0b1622",
    "W": "#f2f9ff",
}


DOLPHIN = Sprite(
    width=44,
    height=22,
    rows=(
        "............................................",
        ".................S..........................",
        "................SDSS........................",
        "................SEDDSS......................",
        ".S...............SEEDDS.....................",
        "SDS..............SEEEEDSS....S..............",
        "DEDS............SSSEEEEDDSSSSDS.............",
        "EEEDS........SSSDDDDDDDDDDDDDDDSSS..........",
        "SEEEDS....SSSDDDDDDDDDDDDDDDDDDDDDSSS.......",
        ".SEEEDSSSSDDDDDMMMMMMMMMMMMMMMMMMDDWKSSSSSS.",
        "..SEEEDDDDMMMMMMMMMMMMMMMMMMMMMMMMMKKDDMMMMS",
        "...SMMMMMMMMMMMMMMMMMMMMMMLLMMMLLMMLMDDDDDDD",
        "...SEPPLLLLLLLLLLLLLLLLLLLLLLLLLLLLPPPMMMMMS",
        "..SDEESSPPPPPPLLLLLLLLLLLLLLLPPPPPPPSSSSSSS.",
        ".SDEES..SSPPPPPPPPPPPPPPPPPPPPPPPPSS........",
        "SDEES.....SSSSPPPPPPPPPPPPPPPPPSSS..........",
        "DEES..........SSSSSSPPPPPSSEEES.............",
        "SEES................SSSSSSDESS..............",
        "SES.....................SDES................",
        ".S.....................SDSS.................",
        "......................SDS...................",
        ".......................S....................",
    ),
)

DOLPHIN_SMALL = Sprite(
    width=30,
    height=14,
    rows=(
        "...........S..................",
        "..........SDSS................",
        "...........SDDSS..............",
        "SS..........SEDDSSSSS.........",
        "DDS......SSSSDDDDDDDDSS.......",
        "SEDS..SSSDDDDDDDDDDDDDDSSSSSS.",
        ".SEDSSDDMMMMMMMMMMMMMMMMWKMMMS",
        "..SLMMMMMMMMMLLLLLLLLLLLKDDDDD",
        ".SDESPPPLLLLLLLLLLLLLPPPPSSSSS",
        "SDES.SSSPPPPPPPPPPPPPPPSS.....",
        "DES.....SSSSSSPPPSSESSS.......",
        "SS............SSSDDS..........",
        "...............SDSS...........",
        "................S.............",
    ),
)

DOLPHIN_TINY = Sprite(
    width=22,
    height=10,
    rows=(
        ".........S............",
        "S.......SDSS..........",
        "DS......SEDDSSSS......",
        "EDS..SSSDDDDDDDDSSSSS.",
        "SEDSSDDMMMMMMMMMMWKMMS",
        ".SLLLLLLLLLLLLLLLKDDDD",
        "SDESSPPPPPPPPPPPPSSSSS",
        "DES..SSSSSPPSSESS.....",
        "SS........SSDSS.......",
        "............S.........",
    ),
)
